language: python

python:
  - "3.6"

service:
  - postgresql 

# command to install python dependencies
install:
 - pip install -r requirements.txt
 - pip install coveralls

before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'create database shoppinglist;' -U postgres
  - export DATABASE_URL="postgresql://postgres@localhost/shoppinglist"
  - python manage.py db upgrade

# command to run tests
script: pytest tests/test_shoppinglist.py