"""empty message

Revision ID: 268ddd907f49
Revises: 70101e1ea14c
Create Date: 2017-10-22 15:49:44.477722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268ddd907f49'
down_revision = '70101e1ea14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(length=500), nullable=False),
                    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
