"""empty message

Revision ID: 70101e1ea14c
Revises:
Create Date: 2017-10-12 17:04:00.470046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70101e1ea14c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'email',
            sa.String(
                length=256),
            nullable=False),
        sa.Column(
            'password',
            sa.String(
                length=256),
            nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'))
    op.create_table('shoppinglist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('item_shoppinglist',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('shoppinglist_id', sa.Integer(), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['shoppinglist_id'], ['shoppinglist.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_shoppinglist')
    op.drop_table('shoppinglist')
    op.drop_table('users')
    # ### end Alembic commands ###
