"""empty message

Revision ID: 9595ffd758c6
Revises: 268ddd907f49
Create Date: 2017-11-17 10:07:11.233165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9595ffd758c6'
down_revision = '268ddd907f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'item_shoppinglist',
        sa.Column(
            'description',
            sa.String(
                length=255),
            nullable=True))
    op.add_column(
        'shoppinglist',
        sa.Column(
            'description',
            sa.String(
                length=255),
            nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglist', 'description')
    op.drop_column('item_shoppinglist', 'description')
    # ### end Alembic commands ###
